name: demo input
on: 
  workflow_dispatch:
    inputs:
      environment-demo:
          description: to give env value
          required: true
          default: dev
jobs:
  input-job:
    runs-on: ubuntu-latest
    steps:
      - name: input demo
        run: echo "deploy application to ${{inputs.environment-demo}}"
      
