name: demo input
on: 
  workflow_dispatch:
    inputs:
      environment-demo:
          description: to give env value
          required: true
          default: dev
      tags:
          description: tag app version
          required: true
          default: 1.0.0
jobs:
  input-job:
    runs-on: ubuntu-latest
    steps:
      - name: input demo
        run: echo "deploy the application version ${{inputs.tags}} to ${{inputs.environment-demo}}"
      
